name: rust test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: rust-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/setup-rust
      - run: cargo test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/setup-rust
      - run: cargo build --release

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/setup-rust
      - name: Check code formatting
        run: cargo fmt -- --check
      - name: Run Clippy for linting
        run: cargo clippy -- -D warnings
