name: rust test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: rust-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: jdx/mise-action@v3.6.1
      - uses: Swatinem/rust-cache@v2.8.2
      - run: cargo test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: jdx/mise-action@v3.6.1
      - uses: Swatinem/rust-cache@v2.8.2
      - run: cargo build --release

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: jdx/mise-action@v3.6.1
      - name: Install static analysis tools
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2.8.2
      - name: Check code formatting
        run: cargo fmt -- --check
      - name: Run Clippy for linting
        run: cargo clippy -- -D warnings
