name: rust test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: rust-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: jdx/mise-action@v3.6.1
      - uses: Swatinem/rust-cache@v2.0.0
      - run: cargo test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: jdx/mise-action@v3.6.1
      - uses: Swatinem/rust-cache@v2.0.0
      - run: cargo build --release

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: jdx/mise-action@v3.6.1
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2.0.0
      - run: cargo clippy -- -D warnings
